# automatically generated by the FlatBuffers compiler, do not modify

# namespace: minia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FlatInt64Value(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatInt64Value()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlatInt64Value(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlatInt64Value
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlatInt64Value
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def FlatInt64ValueStart(builder):
    builder.StartObject(1)

def Start(builder):
    FlatInt64ValueStart(builder)

def FlatInt64ValueAddValue(builder, value):
    builder.PrependInt64Slot(0, value, 0)

def AddValue(builder, value):
    FlatInt64ValueAddValue(builder, value)

def FlatInt64ValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return FlatInt64ValueEnd(builder)
