# automatically generated by the FlatBuffers compiler, do not modify

# namespace: minia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FlatNil(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatNil()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlatNil(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlatNil
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FlatNilStart(builder):
    builder.StartObject(0)

def Start(builder):
    FlatNilStart(builder)

def FlatNilEnd(builder):
    return builder.EndObject()

def End(builder):
    return FlatNilEnd(builder)
