# automatically generated by the FlatBuffers compiler, do not modify

# namespace: minia

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FlatFloatValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatFloatValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlatFloatValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlatFloatValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlatFloatValue
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def FlatFloatValueStart(builder):
    builder.StartObject(1)

def Start(builder):
    FlatFloatValueStart(builder)

def FlatFloatValueAddValue(builder, value):
    builder.PrependFloat32Slot(0, value, 0.0)

def AddValue(builder, value):
    FlatFloatValueAddValue(builder, value)

def FlatFloatValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return FlatFloatValueEnd(builder)
