# automatically generated by the FlatBuffers compiler, do not modify

# namespace: minia

class FlatValue(object):
    NONE = 0
    FlatInt64Value = 1
    FlatFloatValue = 2
    FlatStringValue = 3
    FlatInt64Array = 4
    FlatFloatArray = 5
    FlatStringArray = 6
    FlatNil = 7
